### ISSUE TITLE
Cannot talk to myself

### ISSUE THREAD

**Issue by Urammar** [getnamo/TCP-Unreal#10]
Testing multiplayer locally I am unable to get the server and client to talk to eachother at all? No error messages or anything, it just doesnt seem to happen?

I'm using a single blueprint and a "switch has authority" node to have one add a server component and the other add a client component

**Comment by getnamo** [comment]
One client needs the server component and the other should use the client component. Client should connect to server IP and port

**Comment by Urammar** [comment]
The issue is dynamically spawning these after launch, they need to exist in the world on startup, they cannot or will not always, unsure, wrap later.
